.DEFAULT_GOAL := help
SHELL := /bin/bash

API_DIR := apps/api
WEB_DIR := apps/web
COMPOSE := docker compose --env-file .env -f infra/compose/docker-compose.dev.yml

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "}; /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

## ── Bootstrap ────────────────────────────────────────────────

.PHONY: check
check: ## Verify required tools (uv, pnpm, node, docker, ...) are installed
	@bash scripts/check-tools.sh

.PHONY: install
install: check install-api install-web ## Verify tools, then install all deps

.PHONY: install-api
install-api: ## Install Python deps via uv
	cd $(API_DIR) && uv sync --all-extras

.PHONY: install-web
install-web: ## Install Node deps via pnpm
	pnpm install

## ── Local dev ────────────────────────────────────────────────

.PHONY: up
up: ## Start infra (postgres, redis, mailhog, ...)
	$(COMPOSE) up -d

.PHONY: down
down: ## Stop infra
	$(COMPOSE) down

.PHONY: logs
logs: ## Follow infra logs
	$(COMPOSE) logs -f

.PHONY: dev
dev: up ## Start full dev stack (infra + api + web)
	@echo "Infra is up. In separate terminals run:"
	@echo "  make dev-api"
	@echo "  make dev-web"

# Loopback by default: a dev server should not be on the LAN. Prometheus runs
# in Docker and reaches the host through host-gateway, so scraping needs
# `make dev-api API_HOST=0.0.0.0`.
API_HOST ?= 127.0.0.1

.PHONY: dev-api
dev-api: ## Run API with hot reload (API_HOST=0.0.0.0 to let Prometheus scrape it)
	cd $(API_DIR) && uv run uvicorn zk2.main:app --reload --port 8000 --host $(API_HOST)

.PHONY: dev-web
dev-web: ## Run web with hot reload
	pnpm --filter web dev

.PHONY: dev-worker
dev-worker: ## Run Arq worker
	cd $(API_DIR) && uv run arq zk2.jobs.WorkerSettings

## ── Database ─────────────────────────────────────────────────

.PHONY: migrate
migrate: ## Apply migrations
	cd $(API_DIR) && uv run alembic upgrade head

.PHONY: migrate-down
migrate-down: ## Rollback one migration
	cd $(API_DIR) && uv run alembic downgrade -1

.PHONY: migrate-new
migrate-new: ## Generate new migration: make migrate-new name="add_xxx"
	cd $(API_DIR) && uv run alembic revision --autogenerate -m "$(name)"

.PHONY: seed
seed: ## Seed the super-admin and a workspace to sign into
	cd $(API_DIR) && uv run python -m scripts.seed

.PHONY: seed-demo
seed-demo: ## Add demo documents, a bot, a pipeline and a golden set
	cd $(API_DIR) && uv run python -m scripts.seed_demo

.PHONY: seed-demo-indexed
seed-demo-indexed: ## Same, but index the documents now (spends embedding tokens)
	cd $(API_DIR) && uv run python -m scripts.seed_demo --ingest

## ── Quality ──────────────────────────────────────────────────

.PHONY: lint
lint: lint-api lint-web ## Lint everything

.PHONY: lint-api
lint-api: ## Ruff + mypy on api
	cd $(API_DIR) && uv run ruff check src tests scripts
	cd $(API_DIR) && uv run ruff format --check src tests scripts
	cd $(API_DIR) && uv run mypy src scripts

.PHONY: lint-web
lint-web: ## ESLint + tsc on web
	pnpm --filter web lint
	pnpm --filter web typecheck

.PHONY: format
format: ## Auto-format everything
	cd $(API_DIR) && uv run ruff format src tests
	cd $(API_DIR) && uv run ruff check --fix src tests
	pnpm prettier --write "apps/web/src/**/*.{ts,tsx,js,jsx,json,md}"

## ── Tests ────────────────────────────────────────────────────

.PHONY: test
test: test-api test-web ## Run all tests

.PHONY: test-api
test-api: ## Pytest with testcontainers
	cd $(API_DIR) && uv run pytest -v

.PHONY: test-web
test-web: ## Vitest
	pnpm --filter web test

.PHONY: e2e
e2e: ## Playwright e2e
	pnpm --filter web e2e

## ── API docs ─────────────────────────────────────────────────

.PHONY: openapi
openapi: ## Export the OpenAPI spec and a standalone Redoc page
	cd $(API_DIR) && uv run python -m scripts.export_openapi ../../docs/api

## ── Types ────────────────────────────────────────────────────

.PHONY: gen-types
gen-types: ## Regenerate TS types from API OpenAPI
	cd $(API_DIR) && uv run python -c "import json; from zk2.main import app; print(json.dumps(app.openapi()))" > ../../packages/shared-types/openapi.json
	pnpm --filter shared-types gen

## ── Infrastructure ───────────────────────────────────────────

.PHONY: helm-lint
helm-lint: ## Lint and render the Helm chart for every environment
	helm lint infra/helm/zk2
	for env in dev staging prod; do \
		helm template zk2 infra/helm/zk2 -f infra/helm/zk2/values-$$env.yaml > /dev/null || exit 1; \
	done
	@echo "chart renders for dev, staging and prod"

.PHONY: k8s-manifests
k8s-manifests: ## Re-render infra/k8s from the chart
	@{ echo "# Generated by: make k8s-manifests"; \
	   echo "# Source of truth is the Helm chart in infra/helm/zk2 - edit that, not this."; \
	   helm template zk2 infra/helm/zk2 -f infra/helm/zk2/values-prod.yaml; } > infra/k8s/zk2-prod.yaml
	@echo "infra/k8s/zk2-prod.yaml regenerated"

.PHONY: tf-validate
tf-validate: ## Validate the Terraform example
	cd infra/terraform/envs/dev && terraform init -backend=false -input=false >/dev/null && terraform validate

## ── Production (single host, compose) ────────────────────────

# The whole stack on one machine: postgres, redis, api, worker, web and the
# Caddy that fronts them. Observability rides along in the `obs` profile -
# drop it with `make prod-up PROD_PROFILES=`.
PROD_PROFILES ?= --profile obs
PROD_COMPOSE := docker compose --env-file .env.prod -f infra/compose/docker-compose.prod.yml $(PROD_PROFILES)

.PHONY: prod-config
prod-config: ## Validate the production compose file and its variables
	$(PROD_COMPOSE) config -q && echo "compose config is valid"

.PHONY: prod-build
prod-build: ## Build the api and web images on this host
	$(PROD_COMPOSE) build

.PHONY: prod-up
prod-up: ## Start the production stack (migrations run first)
	$(PROD_COMPOSE) up -d

.PHONY: prod-down
prod-down: ## Stop the production stack, keeping volumes
	$(PROD_COMPOSE) down

.PHONY: prod-ps
prod-ps: ## Show what is running
	$(PROD_COMPOSE) ps

.PHONY: prod-logs
prod-logs: ## Follow logs (make prod-logs SERVICE=api for one service)
	$(PROD_COMPOSE) logs -f --tail=200 $(SERVICE)

.PHONY: prod-migrate
prod-migrate: ## Apply migrations without restarting anything
	$(PROD_COMPOSE) run --rm migrate

.PHONY: prod-seed
prod-seed: ## Seed the super-admin and a workspace to sign into
	$(PROD_COMPOSE) run --rm api python -m scripts.seed

.PHONY: prod-seed-demo
prod-seed-demo: ## Add demo documents, a bot, a pipeline and a golden set
	$(PROD_COMPOSE) run --rm api python -m scripts.seed_demo

.PHONY: prod-deploy
prod-deploy: prod-build prod-up ## Rebuild the images and roll the stack over
	$(PROD_COMPOSE) ps

## ── Clean ────────────────────────────────────────────────────

.PHONY: clean
clean: ## Remove build artefacts and caches
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type d -name .pytest_cache -prune -exec rm -rf {} +
	find . -type d -name .mypy_cache -prune -exec rm -rf {} +
	find . -type d -name .ruff_cache -prune -exec rm -rf {} +
	find . -type d -name .next -prune -exec rm -rf {} +
	find . -type d -name node_modules -prune -exec rm -rf {} +
