apiVersion: v1
kind: Service
metadata:
  name: {{ include "zk2.fullname" . }}-api
  labels: {{- include "zk2.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "zk2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zk2.fullname" . }}-web
  labels: {{- include "zk2.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "zk2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
