{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zk2.serviceAccountName" . }}
  labels: {{- include "zk2.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # IRSA role annotation goes here: the pod gets AWS access without a key file
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
